package contest.winter2017.ohsfile;

import java.util.Arrays;

import com.troyberry.util.data.*;

/**
 * Represents a entry in a main file. The entry is a simplified version of OHS file containing basic information about tests passed failed etc.
 * @author Troy Neubauer
 *
 */
public class MainFileEntry {
	private long timestamp;
	private byte[] hashOfJarFile;
	private int passCount, failCount;
	private float totalPercentCovered;
	private String jarFileName, name = new String();
	private int secutiryTestCount;
	
	public MainFileEntry() {
		this.hashOfJarFile = new byte[16];
	}
	
	public MainFileEntry(OHSFile file) {
		this.name = file.getName();
		this.timestamp = file.getTimestamp();
		this.hashOfJarFile = file.getHashOfJarFile();
		this.passCount = file.getPassCount();
		this.failCount = file.getFailCount();
		this.totalPercentCovered = (float)file.getTotalPercentCovered();
		this.jarFileName = file.getJarFileName();
		this.secutiryTestCount = file.getSecurityTests().size();
	}

	/**
	 * Writes this entry to the writer. Assuming that the writer is in the right place
	 * @param writer The writer to write to
	 */
	public void write(TroyWriter writer) {
		writer.writeString((name == null || name.isEmpty()) ? timestamp + "" : name);
		writer.writeLong(timestamp);
		writer.writeBytes(hashOfJarFile);
		writer.writeString(jarFileName);
		writer.writeInt(passCount);
		writer.writeInt(failCount);
		writer.writeFloat(totalPercentCovered);
		writer.writeInt(secutiryTestCount);
	}
	
	/**
	 * Reads the data about this Entry from a reader. Assumes that the reader is in the right place and has data to read.
	 * @param reader The reader to read from
	 */
	public void read(TroyReader reader) {
		name = reader.readString();
		timestamp = reader.readLong();
		for(int i = 0; i < hashOfJarFile.length; i++) {
			hashOfJarFile[i] = reader.readByte();
		}
		jarFileName = reader.readString();
		passCount = reader.readInt();
		failCount = reader.readInt();
		totalPercentCovered = reader.readFloat();
		secutiryTestCount = reader.readInt();
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

	public byte[] getHashOfJarFile() {
		return hashOfJarFile;
	}

	public void setHashOfJarFile(byte[] hashOfJarFile) {
		this.hashOfJarFile = hashOfJarFile;
	}

	public int getPassCount() {
		return passCount;
	}

	public void setPassCount(int passCount) {
		this.passCount = passCount;
	}

	public int getFailCount() {
		return failCount;
	}

	public void setFailCount(int failCount) {
		this.failCount = failCount;
	}

	public float getPercentCoveredForBasicTests() {
		return totalPercentCovered;
	}

	public void setPercentCoveredForBasicTests(float percentCoveredForBasicTests) {
		this.totalPercentCovered = percentCoveredForBasicTests;
	}

	public String getJarFileName() {
		return jarFileName;
	}

	public void setJarFileName(String jarFileName) {
		this.jarFileName = jarFileName;
	}

	public int getSecutiryTestCount() {
		return secutiryTestCount;
	}

	public void setSecutiryTestCount(int secutiryTestCount) {
		this.secutiryTestCount = secutiryTestCount;
	}
	
	public String getName() {
		if(name.isEmpty())return timestamp + "";
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}

	@Override
	//Messy equals method generated by eclipse
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MainFileEntry other = (MainFileEntry) obj;
		if (failCount != other.failCount)
			return false;
		if (!Arrays.equals(hashOfJarFile, other.hashOfJarFile))
			return false;
		if (jarFileName == null) {
			if (other.jarFileName != null)
				return false;
		} else if (!jarFileName.equals(other.jarFileName))
			return false;
		if (passCount != other.passCount)
			return false;
		if (totalPercentCovered != other.totalPercentCovered)
			return false;
		if (secutiryTestCount != other.secutiryTestCount)
			return false;
		if (timestamp != other.timestamp)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "MainFileEntry [name="+name+", timestamp=" + timestamp + ", hashOfJarFile=" + Arrays.toString(hashOfJarFile)
				+ ", passCount=" + passCount + ", failCount=" + failCount + ", percentCoveredForBasicTests="
				+ totalPercentCovered + ", jarFileName=" + jarFileName + ", secutiryTestCount="
				+ secutiryTestCount + "]";
	}
	
	
}
